<div class="row">
    <div class="col-sm-3 col-md-3 fixCategories hidden-xs">
        <?php if (isset($this->genres) and is_array($this->genres)): ?>
            <ul class="list-group">
                <?php foreach ($this->genres['genres'] as $genre): ?>
                    <li class="list-group-item"><a href="<?php echo ngfw\Uri::baseUrl() . ngfw\Registry::get("requestedLanguage"); ?>/genre/<?php echo $genre['id']; ?>/<?php echo urlencode($genre['name']); ?>"><?php echo $genre['name']; ?></a></li>
                <?php endforeach; ?>   
            </ul>
        <?php endif; ?>
    </div>
    <div class="col-sm-9 col-md-9">
        <?php
        $years = range('1940', date("Y") + 1);
        $decades = array();
        foreach ($years as $year):
            $decade = floor($year / 10) * 10;
            $decades[$decade][] = $year;
        endforeach;
        $decades = array_reverse($decades, true);
        ?>
        <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li class="visible-xs"><a href="<?php echo ngfw\Uri::baseUrl() . ngfw\Registry::get("requestedLanguage"); ?>" class="g-icon micon-home menuLink"><?php echo $this->translation['home']; ?></a></li>
                    <li class="visible-xs"><a href="<?php echo ngfw\Uri::baseUrl() . ngfw\Registry::get("requestedLanguage"); ?>/popular" class="g-icon micon-fire menuLink"><?php echo $this->translation['popularMovies']; ?></a></li>
                    <li class="visible-xs"><a href="<?php echo ngfw\Uri::baseUrl() . ngfw\Registry::get("requestedLanguage"); ?>/popularpeople" class="g-icon micon-users menuLink"><?php echo $this->translation['popularPeople']; ?></a></li>
                    <?php
                        if(isset($this->objects['pages']) and !empty($this->objects['pages'])):
                            foreach($this->objects['pages'] as $key => $page):
                                switch($page['Title']):
                                    case "About us":
                                        ?><li class="visible-xs"><a href="<?php echo ngfw\Uri::baseUrl().ngfw\Registry::get("requestedLanguage")."/page/".$page['Slug']; ?>" class="g-icon micon-info menuLink"><?php echo isset($this->translation[$page['Slug']]) ? $this->translation[$page['Slug']]: $page['Title'];?></a></li><?php
                                    break;
                                    case "Privacy Policy":
                                        ?><li class="visible-xs"><a href="<?php echo ngfw\Uri::baseUrl().ngfw\Registry::get("requestedLanguage")."/page/".$page['Slug']; ?>" class="g-icon micon-lock menuLink"><?php echo isset($this->translation[$page['Slug']]) ? $this->translation[$page['Slug']]: $page['Title'];?></a></li><?php
                                    break;
                                    case "Terms and Conditions":
                                        ?><li class="visible-xs"><a href="<?php echo ngfw\Uri::baseUrl().ngfw\Registry::get("requestedLanguage")."/page/".$page['Slug']; ?>" class="g-icon micon-file menuLink"><?php echo isset($this->translation[$page['Slug']]) ? $this->translation[$page['Slug']]: $page['Title'];?></a></li><?php
                                    break;
                                    case "Contact us":
                                        ?><li class="visible-xs"><a href="<?php echo ngfw\Uri::baseUrl().ngfw\Registry::get("requestedLanguage")."/page/".$page['Slug']; ?>" class="g-icon micon-envelope menuLink"><?php echo isset($this->translation[$page['Slug']]) ? $this->translation[$page['Slug']]: $page['Title'];?></a></li><?php
                                    break;
                                endswitch;
                            endforeach;
                        endif;
                        ?>
                    <li class="dropdown visible-xs">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translation['genres'];?><b class="caret"></b></a>
                        <?php if (isset($this->genres) and is_array($this->genres)): ?>
                            <ul class="dropdown-menu">
                                <?php foreach ($this->genres['genres'] as $genre): ?>
                                    <li><a href="<?php echo ngfw\Uri::baseUrl() . ngfw\Registry::get("requestedLanguage"); ?>/genre/<?php echo $genre['id']; ?>/<?php echo urlencode($genre['name']); ?>"><?php echo $genre['name']; ?></a></li>
                                <?php endforeach; ?>   
                            </ul>
                        </li>
                    <?php endif; ?>
                    <?php foreach ($decades as $decade => $years): ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $decade; ?> <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <?php foreach ($years as $year): ?>    
                                    <li><a href="<?php echo ngfw\Uri::baseUrl() . ngfw\Registry::get("requestedLanguage") . "/sort/year/" . $year; ?>"><?php echo $year; ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </nav>
        <div class="clearfix"></div>
        <div class="col-sm-6 col-md-8 movieListing">
            <h4><?php echo $this->translation['nowPlaying']; ?> <span class="pull-right"><a href="<?php echo ngfw\Uri::baseUrl() . ngfw\Registry::get("requestedLanguage"); ?>/feed/rss/nowplaying"><img src="Assets/img/rss.png"/></a></span></h4>
            <div class="clearfix"></div>
            <?php
            $movieCounter = 0;
            foreach ($this->nowPlaying as $key => $nowPlaying):
                if ($movieCounter < 18):
                    $movieURL = ngfw\Uri::baseUrl() . ngfw\Registry::get("requestedLanguage") . "/movie/" . $nowPlaying['id'] . "/" . urlencode($nowPlaying['title'] . "-" . substr($nowPlaying['release_date'], 0, 4));
                    if (!isset($nowPlaying['poster_path']) or empty($nowPlaying['poster_path'])):
                        continue; // comment out this line if you want to display movies without posters
                        $coverURL = $originalImageUrl = "Assets/img/noposter.jpg";
                    else:
                        $coverURL = $this->mediumThumb . $nowPlaying['poster_path'];
                        $originalImageUrl = $this->originalImage . $nowPlaying['poster_path'];
                    endif;
                    $movieCounter++;
                    ?>
                    <div class="col-xs-6 col-sm-12 col-md-6 col-lg-4">
                        <div class="container-item">
                            <div class="item">
                                <a href="<?php echo $movieURL; ?>"><img src="<?php echo $coverURL; ?>" class="listCover" alt="<?php echo $nowPlaying['title']; ?>" /></a>
                                <div class="item-overlay">
                                    <a href="javascript:void(0);" data-key="<?php echo $key; ?>" class="hidden-xs item-button share share-btn micon-list"></a>
                                </div>
                                <div class="item-content">
                                    <div class="item-top-content-inner">
                                        <div class="item-top-title">
                                            <a href="<?php echo $movieURL; ?>"><?php echo $nowPlaying['title']; ?></a>
                                        </div>
                                    </div>  
                                </div>
                            </div>
                            <div class="hidden-xs item-menu popout-menu popout<?php echo $key; ?>" data-key="<?php echo $key; ?>">
                                <ul>
                                    <li>
                                        <a href="#" data-url="<?php echo $movieURL; ?>" class="gplusShare"><span class="micon-google-plus"></span> +1</a>
                                    </li>
                                    <li>
                                        <a href="#" data-url="<?php echo $movieURL; ?>" data-media="<?php echo $originalImageUrl; ?>" data-description="<?php echo $nowPlaying['title']; ?>" class="pinitShare"> <span class="micon-pinterest"></span> Pinit</a>
                                    </li>
                                    <li>
                                        <a href="#" data-text="<?php echo $nowPlaying['title'] . " " . $movieURL; ?>" class="popout-menu-item twitterShare"> <span class="micon-twitter"></span> Tweet</a></li>
                                    <li><a href="#" data-url="<?php echo $movieURL; ?>" class="popout-menu-item facebookShare"> <span class="micon-facebook"></span> Share</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <?php
                endif;
            endforeach;
            ?>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="clearfix"></div>
            <h4><?php echo $this->translation['upcomingMovies']; ?> <span class="pull-right"><a href="<?php echo ngfw\Uri::baseUrl() . ngfw\Registry::get("requestedLanguage"); ?>/feed/rss/upcoming"><img src="Assets/img/rss.png"/></a></span></h4>
            <div class="clearfix"></div>
            <div class="upcomingWrapper">
                <?php
                foreach ($this->upcoming as $key => $upcoming):
                    if ($key < 10):
                        $movieURL = ngfw\Uri::baseUrl() . ngfw\Registry::get("requestedLanguage") . "/movie/" . $upcoming['id'] . "/" . urlencode($upcoming['title'] . "-" . substr($upcoming['release_date'], 0, 4));
                        if (!isset($upcoming['poster_path']) or empty($upcoming['poster_path'])):
                            $coverURL = $originalImageUrl = "Assets/img/noposter.jpg";
                        else:
                            $coverURL = $this->smallThumb . $upcoming['poster_path'];
                            $originalImageUrl = $this->originalImage . $upcoming['poster_path'];
                        endif;
                        ?>
                        <div class="media mediaupcoming">
                            <a class="pull-left" href="<?php echo $movieURL; ?>">
                                <img class="media-object" src="<?php echo $coverURL; ?>" alt="<?php echo $upcoming['title']; ?>"></a>
                            <div class="media-body">
                                <p class="media-heading"><a href="<?php echo $movieURL; ?>"><?php echo $upcoming['title']; ?></a></p>
                                <a href="#" data-url="<?php echo $movieURL; ?>" class="gplusShare"><span class="micon-google-plus"></span> +1</a>
                                <br />
                                <a href="#" data-url="<?php echo $movieURL; ?>" data-media="<?php echo $originalImageUrl; ?>" data-description="<?php echo $upcoming['title']; ?>" class="pinitShare"> <span class="micon-pinterest"></span> Pinit</a>
                                <br />
                                <a href="#" data-text="<?php echo $upcoming['title'] . " " . $movieURL; ?>" class="popout-menu-item twitterShare"> <span class="micon-twitter"></span> Tweet</a>
                                <br />
                                <a href="#" data-url="<?php echo $movieURL; ?>" class="popout-menu-item facebookShare"> <span class="micon-facebook"></span> Share</a>
                            </div>
                        </div>
                        <?php
                    endif;
                endforeach;
                ?>
            </div>
        </div>         
    </div>
</div>
