<?php
if (isset($this->role) and $this->role == "edit"):
    ?>
    <div class = "row">
      <div class = "col-md-12">
        <div class="jumbotron">
          <h3><?php echo $this->translation['edit_the_ads'];?></h3>
          <form method="post">
              <input type="hidden" name="adID" value="<?php echo $this->ad['adID'];?>"/>
              <input type="text" class="form-control" name="adSize" placeholder ="<?php echo $this->translation['ad_size'];?>" value="<?php echo $this->ad['adSize'];?>" />
              <textarea class="form-control" name="adValue" placeholder ="<?php echo $this->translation['ad_value'];?>" ><?php echo $this->ad['adValue'];?></textarea>
              <input type="submit" value="<?php echo $this->translation['edit'];?>" class="btn btn-primary"/>        
          </form>
        </div>
      </div>
    </div>
<?php
else:
?>
<div class="row">
	<div class="col-md-9">
		<h3><?php echo $this->translation['ads'];?></h3>
	</div>
  <div class="col-md-3" align="right">
    <a href="javascript:void(0);" class="btn btn-primary addAd"><?php echo $this->translation['add_ad'];?></a>
    <script>
                $(function(){
                    $(".addAd").click(function(){
                        $("#addNewAd").removeClass("hide").show();
                        $(this).attr('disabled', 'disabled');
                    });
                    $(".closeNewSetting").click(function() {
                        $(".addAd").removeAttr('disabled');
                        $("#addNewAd").slideUp();
                    });
                });
            </script>            
  </div>
  <div class="col-md-12 hide" id="addNewAd">
    <div class="jumbotron" style="position:relative">
      <h4><?php echo $this->translation['add_ad'];?></h4>
      <form method="post">
        <input type="text" class="form-control" name="size" placeholder ="<?php echo $this->translation['ad_size'];?>" />
        <textarea class="form-control" name="value" placeholder ="<?php echo $this->translation['ad_value'];?>" ></textarea>
        <input type="submit" value="<?php echo $this->translation['add'];?>" class="btn btn-primary"/>                
      </form>
      <span style="position:absolute; right:10px; top:10px; ">
        <a href="javascript:void(0);" class="close closeNewSetting" style="color:black">×</a>
      </span>
    </div>
  </div>
  <div class="clearfix"></div>
	<div class="col-md-12">
		<table class="table table-striped">
            <thead>
                <tr>
                  
                  <th><?php echo $this->translation['ad_id'];?></th>
                  <th><?php echo $this->translation['ad_size'];?></th>
                  <th><?php echo $this->translation['ad_value'];?></th>
                  <th><?php echo $this->translation['action'];?></th>
                </tr>
            </thead>
            <tbody>
            	<?php 
              if(isset($this->ads) and is_array($this->ads)):
            	foreach($this->ads as $key => $ads): ?>
                <tr>
                  <td><?php echo $ads['adID']; ?></td>
                  <td><?php echo $ads['adSize']; ?></td>
                  <td><pre><?php echo strtr($ads['adValue'],Array("<"=>"&lt;","&"=>"&amp;")); ?></pre></td>
                  <td>
                      
                    <a href="<?php echo ngfw\Uri::baseUrl() . $this->requestedLanguage;?>/admin/action/ads/delete/<?php echo $ads['adID']; ?>" class="confirm-delete"><i class="glyphicon glyphicon-trash"></i></a>
                      &nbsp;&nbsp;
                      <a href="<?php echo ngfw\Uri::baseUrl() . $this->requestedLanguage;?>/admin/action/ads/edit/<?php echo $ads['adID']; ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                  </td>
                </tr>
                <?php endforeach; 
                endif;
                ?>
            </tbody>
        </table>
    </div>
</div>
<?php
endif;
?>