<style>

.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .form-signin-heading,
.form-signin .checkbox {
  margin-bottom: 10px;
}
.form-signin .checkbox {
  font-weight: normal;
}
.form-signin .form-control {
  position: relative;
  font-size: 16px;
  height: auto;
  padding: 10px;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="text"] {
  margin-bottom: -1px;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
</style>
<form class="form-signin" action="<?php echo ngfw\Uri::baseUrl() . $this->requestedLanguage;?>/admin/action/auth" method="post" accept-charset="UTF-8" >
    <h2 class="form-signin-heading"><?php echo $this->translation['please_sign_in'];?></h2>
    <input type="text" name="username" class="form-control" placeholder="<?php echo $this->translation['username'];?>" autofocus>
    <input type="password" name="password" class="form-control" placeholder="Password">
    <?php if (isset($this->error)): ?>
        <div class="alert alert-warning" >
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?php echo $this->translation['username_or_password_is_incorrect'];?>
        </div>
    <?php endif; // if isset error  ?>
    <?php if (isset($this->msg)): ?>
        <div class="alert alert-info" >
            <button type="button" class="close" data-dismiss="alert">×</button>
            <?php echo $this->translation['you_have_successfully_logged_out'];?>
        </div>
    <?php endif; // if isset error  ?>
    <button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->translation['sign_in'];?></button>
</form>
