<?php
if (isset($this->role) and $this->role == "edit"):
    ?>
    <div class = "row">
      <div class = "col-md-12">
        <div class="jumbotron" style="position:relative; font-size:12px">
          <h3><?php echo $this->translation['edit_the_ads'];?></h3>
          
        <form method="post"> 
        <input type="hidden" name="pageID" value="<?php echo $this->page['PageID'];?>"/>
        <input type="text" class="form-control" name="Title" placeholder ="<?php echo $this->translation['page_title'];?>" value="<?php echo $this->page['Title'];?>"  />
        <input type="text" class="form-control" name="Slug" placeholder ="<?php echo $this->translation['page_slug'];?>" value="<?php echo $this->page['Slug'];?>"  />
        <label for="Content"><?php echo $this->translation['page_content'];?></label>
        <textarea class="form-control" name="Content"><?php echo $this->page['Content'];?></textarea>
        <div class="checkbox">
		    <label>
		      <input type="checkbox" name="Active" <?php if($this->page['Active'] == "1"): echo 'checked="checked"';endif;?>> <?php echo $this->translation['active'];?>
		    </label>
		  </div>
        <input type="submit" value="<?php echo $this->translation['edit'];?>" class="btn btn-primary"/>                
      </form>
        </div>
      </div>
    </div>
<?php
else:
?>

<div class="row">
  <div class="col-md-9">
    <h3><?php echo $this->translation['pages'];?></h3>
  </div>
  <div class="col-md-3" align="right">
    <a href="javascript:void(0);" class="btn btn-primary addPage"><?php echo $this->translation['add_page'];?></a>
    <script>
	    $(function(){
	        $(".addPage").click(function(){
	            $("#addNewPage").removeClass("hide").show();
	            $(this).attr('disabled', 'disabled');
	        });
	        $(".closeNewAdmin").click(function() {
	            $(".addPage").removeAttr('disabled');
	            $("#addNewPage").slideUp();
	        });
	        $(".pageTitle").keyup(function(){
        		var str = $(this).val();
				str = str.replace(/[^a-zA-Z0-9\s]/g,"");
				str = str.toLowerCase();
				str = str.replace(/\s/g,'-');
				$(".pageSlug").val(str);
			});
	    });
	</script>            
  </div>
  <div class="col-md-12 hide" id="addNewPage">
    <div class="jumbotron" style="position:relative; font-size:12px">
      <h4><?php echo $this->translation['add_page'];?></h4>
      <form method="post">
        <input type="text" class="form-control pageTitle" name="Title" placeholder ="<?php echo $this->translation['page_title'];?>" />
        <input type="text" class="form-control pageSlug" name="Slug" placeholder ="<?php echo $this->translation['page_slug'];?>" />
        <label for="Content"><?php echo $this->translation['page_content'];?></label>
        <textarea class="form-control" name="Content"></textarea>
        <div class="checkbox">
  		    <label>
  		      <input type="checkbox" name="Active" checked="checked"> <?php echo $this->translation['active'];?>
  		    </label>
  		  </div>
        <input type="submit" value="<?php echo $this->translation['add'];?>" class="btn btn-primary"/>                
      </form>
      <span style="position:absolute; right:10px; top:10px; ">
        <a href="javascript:void(0);" class="close closeNewAdmin" style="color:black">×</a>
      </span>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="col-md-12">
    <table class="table table-striped">
            <thead>
                <tr>
                  <th>#</th>
                  <th><?php echo $this->translation['page_title'];?></th>
                  <th><?php echo $this->translation['page_slug'];?></th>
                  <th><?php echo $this->translation['active'];?></th>
                  <th><?php echo $this->translation['action'];?></th>
                </tr>
            </thead>
            <tbody>
              <?php 
              foreach($this->pages as $key => $page): ?>
                <tr>
                  <td><?php echo $key+1; ?></td>
                  <td><?php echo $page['Title']; ?></td>
                  <td><?php echo $page['Slug']; ?></td>
                  <td><?php 
                  	if($page['Active'] == "1"):
                  		?><span class="label label-success"><?php echo $this->translation['yes']; ?></span><?php 
                  	else:
                  		?><span class="label label-warning"><?php echo $this->translation['no']; ?></span><?php 
                  	endif;
                  	?></td>
                  <td>
                      <a href="<?php echo ngfw\Uri::baseUrl(). $this->requestedLanguage;?>/admin/action/page/delete/<?php echo $page['PageID']; ?>" class="confirm-delete"><i class="glyphicon glyphicon-trash"></i></a>
                      &nbsp;&nbsp;
                      <a href="<?php echo ngfw\Uri::baseUrl(). $this->requestedLanguage;?>/admin/action/page/edit/<?php echo $page['PageID']; ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                  </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php
endif;
?>