<?php
if (isset($this->role) and $this->role == "edit"):
    ?>
    <div class = "row">
      <div class = "col-md-12">
        <div class="jumbotron">
          <h3><?php echo $this->translation['edit_the_setting'];?></h3>
          <form method="post">
              <input type="hidden" name="settingID" value="<?php echo $this->setting['SettingID'];?>"/>
              <input type="text" class="form-control" name="SettingName" placeholder ="<?php echo $this->translation['setting_name'];?>" value="<?php echo $this->setting['SettingName'];?>" />
              <input type="text" class="form-control" name="SettingValue" placeholder ="<?php echo $this->translation['setting_value'];?>" value="<?php echo $this->setting['SettingValue'];?>" />
              <input type="submit" value="<?php echo $this->translation['edit'];?>" class="btn btn-primary"/>        
          </form>
        </div>
      </div>
    </div>
<?php
else:
?>
<div class="row">
	<div class="col-md-9">
		<h3><?php echo $this->translation['settings'];?></h3>
	</div>
	<div class="col-md-3" align="right">
		<a href="javascript:void(0);" class="btn btn-primary addSetting"><?php echo $this->translation['add_setting'];?></a>
    <script>
                $(function(){
                    $(".addSetting").click(function(){
                        $("#addNewSetting").removeClass("hide").show();
                        $(this).attr('disabled', 'disabled');
                    });
                    $(".closeNewSetting").click(function() {
                        $(".addSetting").removeAttr('disabled');
                        $("#addNewSetting").slideUp();
                    });
                });
            </script>            
	</div>
  <div class="col-md-12 hide" id="addNewSetting">
    <div class="jumbotron" style="position:relative">
      <h4><?php echo $this->translation['add_setting'];?></h4>
      <form method="post">
        <input type="text" class="form-control" name="name" placeholder ="<?php echo $this->translation['setting_name'];?>" />
        <input type="text" class="form-control" name="value" placeholder ="<?php echo $this->translation['setting_value'];?>" />
        <input type="submit" value="<?php echo $this->translation['add'];?>" class="btn btn-primary"/>                
      </form>
      <span style="position:absolute; right:10px; top:10px; ">
        <a href="javascript:void(0);" class="close closeNewSetting" style="color:black">×</a>
      </span>
    </div>
  </div>
  <div class="clearfix"></div>
	<div class="col-md-12">
		<table class="table table-striped">
            <thead>
                <tr>
                  <th>#</th>
                  <th><?php echo $this->translation['setting_name'];?></th>
                  <th><?php echo $this->translation['setting_value'];?></th>
                  <th><?php echo $this->translation['action'];?></th>
                </tr>
            </thead>
            <tbody>
            	<?php 

            	foreach($this->settings as $key => $setting): ?>
                <tr>
                  <td><?php echo $key+1; ?></td>
                  <td><?php echo $setting['SettingName']; ?></td>
                  <td><?php echo $setting['SettingValue']; ?></td>
                  <td>
                      <a href="<?php echo ngfw\Uri::baseUrl(). $this->requestedLanguage;?>/admin/action/settings/delete/<?php echo $setting['SettingID']; ?>" class="confirm-delete"><i class="glyphicon glyphicon-trash"></i></a>
                      &nbsp;&nbsp;
                      <a href="<?php echo ngfw\Uri::baseUrl(). $this->requestedLanguage;?>/admin/action/settings/edit/<?php echo $setting['SettingID']; ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                  </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php
endif;
?>